docs/DeveloperGuide.md

Updated the details of target user profile, value proposition and user stories for EduConnect.
To be updated or revised.
Fixes #10

Update DG: User Stories

---

docs/_config.yml
docs/_sass/minima/_base.scss

Update site-wide settings for Jekyll

---

docs/DeveloperGuide.md

Update DG: Glossary

---

docs/DeveloperGuide.md
docs/_config.yml

Add use cases for adding teachers or students, deleting contacts, editing, listing and clearing.
Update config.yml repo link
Fixes #11

Update DG: Use Cases

---

docs/DeveloperGuide.md

Fix minor issue with use case 5

---

src/main/java/seedu/address/logic/commands/ClearCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/ClearCommandParser.java
src/test/java/seedu/address/logic/commands/ClearCommandTest.java
src/test/java/seedu/address/logic/commands/EditCommandTest.java

Create new parser class for Clear command

MVP Feature: Clear Contacts

---

src/test/java/seedu/address/logic/commands/FindCommandTest.java

Add test for find command

---

src/main/java/seedu/address/logic/commands/AddTeacherCommand.java
src/main/java/seedu/address/logic/parser/AddTeacherCommandParser.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/person/Gender.java
src/main/java/seedu/address/model/person/Teacher.java
src/test/java/seedu/address/logic/parser/AddCommandParserTest.java

with Gender class, change CLI prefix to match MVP requirement, requires more test cases from @Arnaxx54 
Fixes #37

Add AddTeacherCommand functionality

---

src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/parser/AddStudentCommandParser.java
src/main/java/seedu/address/model/person/Address.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/parser/AddStudentCommandParserTest.java
src/test/java/seedu/address/model/person/StudentTest.java
src/test/java/seedu/address/model/person/SubjectTest.java
src/test/java/seedu/address/testutil/StudentBuilder.java
src/test/java/seedu/address/testutil/TypicalPersons.java

Add Test Cases for Add Student

---

src/main/java/seedu/address/logic/commands/AddTeacherCommand.java
src/main/java/seedu/address/logic/parser/AddTeacherCommandParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/person/Teacher.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/parser/AddTeacherCommandParserTest.java
src/test/java/seedu/address/model/person/GenderTest.java
src/test/java/seedu/address/model/person/SubjectTest.java
src/test/java/seedu/address/model/person/TeacherTest.java
src/test/java/seedu/address/testutil/TeacherBuilder.java
src/test/java/seedu/address/testutil/TypicalTeachers.java

Add teacher command

---

src/main/java/seedu/address/logic/commands/SortCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/SortCommandParser.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/person/Person.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
src/test/java/seedu/address/logic/commands/SortCommandTest.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
src/test/java/seedu/address/logic/parser/SortCommandParserTest.java

Add sort functionality

---

src/main/java/seedu/address/logic/commands/FindCommand.java
src/main/java/seedu/address/logic/parser/ClearCommandParser.java
src/main/java/seedu/address/logic/parser/FindCommandParser.java
src/main/java/seedu/address/model/person/AddressContainsKeywordsPredicate.java
src/main/java/seedu/address/model/person/EmailContainsKeywordsPredicate.java
src/main/java/seedu/address/model/person/PersonContainsKeywordsPredicate.java
src/main/java/seedu/address/model/person/PhoneContainsKeywordsPredicate.java
src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
src/test/java/seedu/address/logic/commands/FindCommandTest.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
src/test/java/seedu/address/model/person/AddressContainsKeywordsPredicateTest.java
src/test/java/seedu/address/model/person/EmailContainsKeywordsPredicateTest.java
src/test/java/seedu/address/model/person/PersonContainsKeywordsPredicateTest.java
src/test/java/seedu/address/model/person/PhoneContainsKeywordsPredicateTest.java
src/test/java/seedu/address/model/person/TagContainsKeywordsPredicateTest.java

Add Find by tags and keywords feature

---

README.md

Update codecov link

---

src/test/java/seedu/address/logic/commands/AddTeacherCommandTest.java

Resolve issues with ModelStub and merging

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/parser/EditCommandParser.java
src/main/java/seedu/address/ui/PersonCard.java
src/main/java/seedu/address/ui/PersonListPanel.java
src/main/resources/view/DarkTheme.css

Update User Guide

---

docs/diagrams/ModelClassDiagram.puml
docs/diagrams/UndoSequenceDiagram-Model.puml

Update Undo's sequence diagram

---

docs/diagrams/ArchitectureSequenceDiagram.puml
docs/diagrams/BetterModelClassDiagram.puml
docs/diagrams/DeleteSequenceDiagram.puml
docs/diagrams/PersonClass.puml

Modify DeleteCommand related diagrams to highlight bulk delete, add new Person attributes, Add Person class diagram
Fixes #90

UML Update

---

docs/diagrams/MarkAttendanceSequenceDiagram-Logic.puml

Add sequence diagram for MarkAttendanceCommand

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/AddTeacherCommand.java
src/main/java/seedu/address/logic/commands/UnmarkAttendanceCommand.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/person/DaysAttended.java
src/main/java/seedu/address/model/person/Student.java
src/main/java/seedu/address/ui/PersonCard.java
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/commands/UnmarkAttendanceCommandTest.java
src/test/java/seedu/address/model/person/StudentTest.java
src/test/java/seedu/address/testutil/TypicalPersons.java

Fix attendance functionality

---

src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/person/DaysAttended.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/person/Student.java
src/main/java/seedu/address/model/person/Teacher.java
src/main/java/seedu/address/storage/JsonAdaptedPerson.java
src/test/java/seedu/address/logic/commands/UnmarkAttendanceCommandTest.java
src/test/java/seedu/address/model/AddressBookTest.java
src/test/java/seedu/address/model/person/DaysAttendedTest.java
src/test/java/seedu/address/model/person/PersonTest.java
src/test/java/seedu/address/model/person/StudentTest.java
src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java

Fix Undo-Attendance bug

---

docs/UserGuide.md

Add documentation for attendance functionality to UG guide

---

build.gradle
src/main/java/seedu/address/ui/MainWindow.java
src/main/resources/view/LightTheme.css
src/main/resources/view/MainWindow.fxml

Add LightMode Functionality

---

src/main/java/seedu/address/logic/parser/AddStudentCommandParser.java
src/main/java/seedu/address/logic/parser/AddTeacherCommandParser.java
src/main/java/seedu/address/model/person/Address.java
src/main/java/seedu/address/model/person/DaysAttended.java
src/main/java/seedu/address/ui/PersonCard.java
src/test/java/seedu/address/logic/parser/AddTeacherCommandParserTest.java

Update Student and Teacher commands to have even more optional fields than before.
Specifically, attendance and address
Fixes #106

Update Student and Teacher commands to have optional fields

---

src/main/java/seedu/address/ui/CommandHistory.java
src/test/java/seedu/address/ui/CommandHistoryTest.java

Update Command History

---

src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/person/Student.java
src/main/java/seedu/address/model/person/Teacher.java
src/test/java/seedu/address/logic/commands/RedoCommandTest.java
src/test/java/seedu/address/model/AddressBookTest.java
src/test/java/seedu/address/model/person/PersonTest.java
src/test/java/seedu/address/model/person/StudentTest.java
src/test/java/seedu/address/model/person/TeacherTest.java
src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java

Modified Person::isSamePerson check

---

src/main/java/seedu/address/logic/commands/ClearCommand.java
src/test/java/seedu/address/logic/commands/ClearCommandTest.java

Alpha Bug Fix: Update success messages and errors depending on what gets cleared in Clear command

---

src/main/java/seedu/address/ui/HelpWindow.java

Alpha Bug Fix: Update user guide URL in help window

---

src/main/java/seedu/address/model/person/Phone.java
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/model/person/AddressContainsKeywordsPredicateTest.java
src/test/java/seedu/address/model/person/EmailContainsKeywordsPredicateTest.java
src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
src/test/java/seedu/address/model/person/PhoneContainsKeywordsPredicateTest.java
src/test/java/seedu/address/model/person/PhoneTest.java
src/test/java/seedu/address/model/person/TagContainsKeywordsPredicateTest.java
src/test/java/seedu/address/testutil/TypicalPersons.java

to restrict phone numbers to be exactly 8 digits long, in accordance to Singapore local numbers
Fixes #138

Edit Phone::isValidPhone

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/test/java/seedu/address/logic/commands/DeleteCommandTest.java

Add duplicate index handling for bulk DeleteCommand

---

src/main/java/seedu/address/model/person/ClassContainsKeywordsPredicate.java
src/main/java/seedu/address/model/person/PersonContainsKeywordsPredicate.java
src/main/java/seedu/address/model/person/SubjectContainsKeywordsPredicate.java
src/test/java/seedu/address/model/person/ClassContainsKeywordsPredicateTest.java
src/test/java/seedu/address/model/person/PersonContainsKeywordsPredicateTest.java
src/test/java/seedu/address/model/person/SubjectContainsKeywordsPredicateTest.java

Alpha Bug Fix: Update PersonContainsKeywordsPredicate to account for Subject and Classes

---

src/main/java/seedu/address/logic/Messages.java
src/test/java/seedu/address/model/person/ClassContainsKeywordsPredicateTest.java
src/test/java/seedu/address/model/person/PersonTest.java
src/test/java/seedu/address/model/person/SubjectContainsKeywordsPredicateTest.java

Fixes #117 
Fixes #128 
Fixes #137

Resolve add Teacher/Student command success message

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/UnmarkAttendanceCommand.java
src/main/java/seedu/address/logic/parser/UnmarkAttendanceCommandParser.java
src/main/java/seedu/address/model/person/DaysAttended.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/person/Student.java
src/main/java/seedu/address/model/person/Teacher.java
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/commands/UnmarkAttendanceCommandTest.java
src/test/java/seedu/address/logic/parser/UnmarkAttendanceCommandParserTest.java
src/test/java/seedu/address/model/person/DaysAttendedTest.java
src/test/java/seedu/address/model/person/PersonTest.java
src/test/java/seedu/address/model/person/StudentTest.java
src/test/java/seedu/address/model/person/TeacherTest.java
src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
src/test/java/seedu/address/testutil/Assert.java

Fixing Alpha bugs for attendance marking

---

src/main/java/seedu/address/logic/commands/FindCommand.java
src/main/java/seedu/address/model/person/GenderContainsKeywordsPredicate.java
src/main/java/seedu/address/model/person/PersonContainsKeywordsPredicate.java
src/test/java/seedu/address/logic/commands/FindCommandTest.java
src/test/java/seedu/address/model/person/GenderContainsKeywordsPredicateTest.java

Fix Alpha Bugs to improve find functionality

---

src/main/java/seedu/address/logic/commands/EditCommand.java
src/test/java/seedu/address/model/person/ClassContainsKeywordsPredicateTest.java
src/test/java/seedu/address/model/person/SubjectContainsKeywordsPredicateTest.java

Resolve edit command typo in error message, modify test cases related to new isValidPhone

---

src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/ui/MainWindow.java
src/test/java/seedu/address/logic/commands/EditCommandTest.java

Fixes #259 and it's duplicate issues

Fix Edit command duplicate person handling

---

src/main/java/seedu/address/MainApp.java

Fixes #217 
Simply removing traces of AB3 terms in the logger, not an enhancement.

PE-D: Rename AddressBook to EduConnect in logger

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/AddStudentCommand.java
src/main/java/seedu/address/logic/commands/AddTeacherCommand.java
src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
src/test/java/seedu/address/logic/commands/AddTeacherCommandTest.java

Fixes #258 
This fix falls under widening scope of message.

PE-D: Update duplicate person message to be more general

---

src/main/java/seedu/address/model/person/Name.java
src/main/java/seedu/address/model/person/Phone.java

Fixes #220 
We are widening the scope of the error message by adding on more possibilities of what is wrong, so it's an acceptable bug fix according to feature freeze specifications.

PE-D: Update message constraints for name and phone

---

src/main/java/seedu/address/logic/parser/AddStudentCommandParser.java
src/main/java/seedu/address/logic/parser/AddTeacherCommandParser.java

Fixes #211 
Since there was originally duplicate prefix check for Teacher, we are allowed to add it to Student.

PE-D: Add duplicate prefix check for add Student command
